// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzNOEp_CMBxr6q_hlhI_6K0tXo4Vsg9A',
    appId: '1:985454742037:web:cfed2a763350fc759e1c1c',
    messagingSenderId: '985454742037',
    projectId: 'ms-project-bf0b9',
    authDomain: 'ms-project-bf0b9.firebaseapp.com',
    databaseURL: 'https://ms-project-bf0b9-default-rtdb.firebaseio.com',
    storageBucket: 'ms-project-bf0b9.appspot.com',
    measurementId: 'G-P28P4SQGH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZAMgDqQT_sPBLB8PmPMRbqoiitz5ScW0',
    appId: '1:985454742037:android:974238b54c3550039e1c1c',
    messagingSenderId: '985454742037',
    projectId: 'ms-project-bf0b9',
    databaseURL: 'https://ms-project-bf0b9-default-rtdb.firebaseio.com',
    storageBucket: 'ms-project-bf0b9.appspot.com',
  );
}
